#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
./Allrun.pre
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions
echo
runApplication chtMultiRegionFoam
echo
echo "Post-processing now"
echo
./postFunc
paraFoam -touchAll
echo
echo "End"
#------------------------------------------------------------------------------
